apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: mon-application
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
